global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'currency-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.73:8080' ] # use your IP -> TODO use container

  - job_name: 'opening-hours-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.73:8081' ] # use your IP -> TODO use container

  - job_name: 'location-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.73:8082' ] # use your IP -> TODO use container

  - job_name: 'car-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.73:8083' ] # use your IP -> TODO use container

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.73:8084' ] # use your IP -> TODO use container

  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.73:8085' ] # use your IP -> TODO use container

